version: '3'
services:
  todotests:
    build: tests/
    depends_on:
      - todofront
      - todoback
    environment:
      - FRONT_HOST=front-end
    # restart: on-failure
  todofront:
    build: front-end/
    ports:
      - 3000:3000
    depends_on:
      - backend
    environment:
      - REACT_APP_API_HOST=backend
    # restart: on-failure
  todoback:
    build: back-end/
    ports:
      - 3001:3001
    # restart: on-failure